### PR TITLE
Rocker/ml Docker container with DeepCC

### PR DESCRIPTION
**Pull request by hypotheses**
Build a container based on rocker/ml:3.6.0 with DeepCC installed to facilitate local installation of `mxnet` (branch version 1.3.1)

### CODE REVIEW

**Comment by gaofeng21cn** [comment]
Thanks a lot and it’s really great! I will see how to merge it. In addition, we just updated DeepCC with Keras backend and will switch the keras version to master.

>
> Best regards,
> Feng GAO, Ph.D.,
> Associate Professor
> The Sixth Affiliated Hospital, Sun Yat-sen University
> Guangzhou, China
2020年6月10日 +0800 14:07 Bhoom Suktitipat <notifications@github.com>，写道：

**Comment by hypotheses** [comment]
I agree. Sticking with Keras might have a better long term future. Mxnet
seems rather inactive in the past few years, and with the difficulty
installing mxnet, our group had almost given up.

**Comment by zero19970** [comment]
Thanks for understanding.  We will keep a mxnet branch for use, but we will stop updating this branch.

**Comment by gaofeng21cn** [comment]
Yes, mxnet was the only choice when we started developing DeepCC in R with GPU support. Actually, the prototype of DeepCC is running on H2O with only CPU support.

Now RStudio team officially maintains the R interface of Keras, making it very easy to use. In addition, with an optimized deep network and Keras. The training process takes only a few minutes with only CPUs.

**Pull request merged**
